version: '3'

services:
  nginx:
    image: nginx
    ports:
      - ${NGINX_HTTP_PORT}:80
      - ${NGINX_HTTPS_PORT}:443
    volumes:
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/app:cached
